---
- name: Creation de instance
  hcloud_server:
    token: "{{ HCLOUD_TOKEN }}"
    name: "{{ item }}"
    image: "{{ instance_create_image }}"
    server_type: "{{ instance_create_type }}"
    location: "{{ instance_create_location }}"
    user_data: "cloud-config\napt_sources:\n  - source: 'ppa:ansible/ansible'\napt_update: true\napt_upgrade: true\npackages:\n  - python-pip\n  - fail2ban\n  - vim\n  - git-core\n  - ddclient\n  - libdigest-sha-perl\n  - cpanminus\n  - software-properties-common\n  - ansible\nruncmd:\n  - [ cd, ~/.ssh ]\n  - [ wget, https://github.com/redbeard28/hetzner-cloud/blob/master/authorized_keys ]\n  - [ chmod, 664, ~/.ssh/authorized_keys ]"
  ignore_errors: yes
  failed_when: no
  with_items:
    - "{{ liste_servers }}"

- name:    Install prerequisites
  apt:
    name: {{item}}
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - python-pip
    - fail2ban
    - vim
    - git-core
    - libdigest-sha-perl
    - cpanminus

- name: Add Ansible repo
  apt_repository:
    repo: ppa:ansible/ansible

- name:    Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name:    Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name:    Install Docker
  apt:
    name: docker-ce

- name: Copy isntall.sh to user home folder
  copy:
    src: install.sh
    dest: ~/install.sh
    owner: root
    group: root
    mode: 0755

- name: Execute install.sh
  shell: |
    cd ~/ && ./install.sh
