---
- include: deploy.yml
  when: ( instance_create_valide == 'True' )
  tags: create_instance

- include: list.yml
  tags: [ list_instance, create_instance ]

- include: delete.yml
  when: ( instance_delete == 'True' )
  tags: [ delete_instance ]
